In [15]:
import numpy as np

# Check the axes or dimensions of array
matrix_arr = np.array([[1,2,3],
                     [4,5,6],
                     [6,7,8]])
print(matrix_arr.ndim)

# print tha type of object
print(type(matrix_arr))

# print array shape
print(matrix_arr.shape)

# print size of array (Number of elements in array)
print(matrix_arr.size)

2
<class 'numpy.ndarray'>
(3, 3)
9


**Array Creation using Numpy**

 **dtype** can past while creating array as argument to define the type of the array

In [47]:
import numpy as np
matrix_arr = np.array([[1,2,3], [1,2,3]])
# array created using simple array method and passing values in rows and columns
print("Array created simple array ,method")
print(matrix_arr)

# create array by passing tuple to the array
matrix_arr = np.array((1, 2, 3, 4))
print("Array created by using tuple")
print(matrix_arr)

# create array by using np.zeros method
matrix_arr = np.zeros((3,4))
print("Array created by using np.zeros method")
print(matrix_arr)


# create array by using full method
matrix_arr = np.full((2,3),12)
print("Array created by using full method")
print(matrix_arr)

# create array by using arrange method
matrix_arr = np.arange(0,21, 5)
print("Array created by using arange method")
print(matrix_arr)

# create array by using random method
matrix_arr=np.random.randn(2,2)
print("Array created by using random method")
print(matrix_arr)

# create array by using linspace method
matrix_arr=np.linspace(0, 10, 5)
print("Array created by using linspace method")
print(matrix_arr)

matrix_arr=np.array([[1,2,3],
                     [1,2,3],
                     [1,2,3]])
#create a flatten array of the above given array
print(matrix_arr.flatten())

Array created simple array ,method
[[1 2 3]
 [1 2 3]]
Array created by using tuple
[1 2 3 4]
Array created by using np.zeros method
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array created by using full method
[[12 12 12]
 [12 12 12]]
Array created by using arange method
[ 0  5 10 15 20]
Array created by using random method
[[-0.38380794 -0.25135063]
 [-0.07409157  1.46349848]]
Array created by using linspace method
[ 0.   2.5  5.   7.5 10. ]
[1 2 3 1 2 3 1 2 3]


**Array indexing**
-> slicing  -> interger indexing  -> boolean indexing




In [69]:
import numpy as np
matrix_arr = np.array([[1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12],
                     [13,14,15,16]])
print("ORiginal array ")
print(matrix_arr)

#array slicing
print("Print array using slicing")
print("array first three rwos")
print(matrix_arr[:3])

print('Array row index 1 to 2 Here 1 is include and 3 is excluede')
print(matrix_arr[1:3])

print("Print array with slicing by passing secified column slicing")
print('Here we pass 0::2 for column (0::2) 0 and 2 is include (0:2) 0 to 1')

print("0th and 2nd column")
print(matrix_arr[1:3, 0::2])
print('0th to 1st column')
print(matrix_arr[1:3, 0:2])

#First index represent row and second column as 1 row 1 column
arr = matrix_arr[[0, 1, 2, 3], [0, 1, 2, 3]]
print("Printing corresponding rows and column")
print(arr)

# array indexing with specific condition
print(matrix_arr > 2) # it wil craete an array with true and false according the condition

bool_arr=matrix_arr > 5
print(matrix_arr[bool_arr]) # printing the array elements where bool is true as plane array

ORiginal array 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Print array using slicing
array first three rwos
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array row index 1 to 2 Here 1 is include and 3 is excluede
[[ 5  6  7  8]
 [ 9 10 11 12]]
Print array with slicing by passing secified column slicing
Here we pass 0::2 for column (0::2) 0 and 2 is include (0:2) 0 to 1
0th and 2nd column
[[ 5  7]
 [ 9 11]]
0th to 1st column
[[ 5  6]
 [ 9 10]]
Printing corresponding rows and column
[ 1  6 11 16]
[[False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 12 13 14 15 16]


**Numpy arra basic operation**

In [88]:
import numpy as np
matrix_arr = np.array([[1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12],
                     [13,14,15,16]])

matrix_two = np.array([[1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12],
                     [13,14,15,16]])
matrix_one = np.array([[1,2,3,4],
                     [5,6,7,8],
                     [9,10,11,12],
                     [13,14,15,16]])
print("Multiply each number with specified number")
print(matrix_arr * 2)

print("Multiply each number with specified number by using multiply function")
print(np.multiply(matrix_arr, 2))

print("Adding two arrays")
print(matrix_one + matrix_two)

print("subtract two arrays")
print(matrix_one - matrix_two)

print("Element wise multiplication of two arrays")
print(matrix_one * matrix_two) # element wise multiplication each number is multiplied with corresponding number

print("Taking transpose of a mtirx  array")
print(matrix_arr.T)

print("Max value in a array")
print(matrix_arr.max())

print("min value in a array")
print(matrix_arr.min())

print("Max value in a array with row operation and return answer as matrix")
print(matrix_arr.max(axis=1)) # axis=1 represent row operation and axis=0 represent column operation

print("Max value in a array with column operation and return answer as matrix")
print(matrix_arr.max(axis=0)) # axis=1 represent row operation and axis=0 represent column operation

print("Sum of all array elements")
print(matrix_arr.sum())

print("Cumulative sum in row operation ")
print(matrix_arr.cumsum(axis = 1))

print("Cumulative sum in column operation ")
print(matrix_arr.cumsum(axis = 0))

print("Matrix multiplication")
print(matrix_one.dot(matrix_two))

print("Find square root of each element of array")
print(np.sqrt(matrix_arr))


Multiply each number with specified number
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
Multiply each number with specified number by using multiply function
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
Adding two arrays
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
subtract two arrays
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Element wise multiplication of two arrays
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]
 [169 196 225 256]]
Taking transpose of a mtirx  array
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Max value in a array
16
min value in a array
1
Max value in a array with row operation and return answer as matrix
[ 4  8 12 16]
Max value in a array with column operation and return answer as matrix
[13 14 15 16]
Sum of all array elements
136
Cumulative sum in row operation 
[[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]
 [13 27 42 58]]
Cumulative sum in column operation 
[[ 1  2  3  4]
 [ 6  8 10 12]
 [

**Sin values array manipulation**

In [87]:
import numpy as np

sine_arr=np.array([np.pi, np.pi/2, np.pi/3, np.pi/4])
print("sine array")
print(sine_arr)

print("Find sine values of sine array")
print(np.sin(sine_arr))


sine array
[3.14159265 1.57079633 1.04719755 0.78539816]
Find sine values of sine array
[1.22464680e-16 1.00000000e+00 8.66025404e-01 7.07106781e-01]


**Sorting operation on arrays**

In [95]:
import numpy as np
matrix_arr = np.array([[2,3,1,4],
                     [5,6,7,8],
                     [9,10,11,12],
                     [13,14,15,16]])

print("Sort array all elemenst")
print(np.sort(matrix_arr, axis=None))

print("Sort array all elemenst with row and column wise")
print(np.sort(matrix_arr))

print("Sort array all elemenst with row wise")
print(np.sort(matrix_arr, axis=1))

print("Sort array all elemenst with column wise")
print(np.sort(matrix_arr, axis=0))

print("Sort array all elements by providing third argument as kind=sort_kind heap, quick, mergsort")
print(np.sort(matrix_arr, axis=1, kind="heap"))

Sort array all elemenst
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Sort array all elemenst with row and column wise
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sort array all elemenst with row wise
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sort array all elemenst with column wise
[[ 2  3  1  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sort array all elements by providing third argument as kind=sort_kind heap, quick, mergsort
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


**Sorting array with provided data**

In [104]:
from os import name
import numpy as np

dtype = [('name', 'S10'), ('year', int), ('marks', float)]
user_data = [('naseer', 2012, 875), ('ali', 2014, 900)]
user_arr=np.array(user_data, dtype=dtype)
print("Origional array")
print(user_arr)

print("Array sort by name")
print(np.sort(user_arr, order='name'))

print("Array sort by year")
print(np.sort(user_arr, order='year'))

print("Array sort first by name and then  by year")
print(np.sort(user_arr, order=['marks', 'year']))

Origional array
[(b'naseer', 2012, 875.) (b'ali', 2014, 900.)]
Array sort by name
[(b'ali', 2014, 900.) (b'naseer', 2012, 875.)]
Array sort by year
[(b'naseer', 2012, 875.) (b'ali', 2014, 900.)]
Array sort first by name and then  by year
[(b'naseer', 2012, 875.) (b'ali', 2014, 900.)]


**Resize numpy array**
difference between reshape and resize. When we talk about reshape then an array changes it’s shape as temporary but when we talk about resize then the changes made permanently

In [119]:
import numpy as np

matrix_arr = np.array([1, 2, 3, 4, 5, 6])
print("Pritn 1 by 7 array")
print(matrix_arr)

print("Reshape the matrix given above")
print(np.reshape(matrix_arr, (2,3))) # it change the size of matrix temporarily

print("Array after reshping the array")
matrix_arr.resize(2, 3)
print(matrix_arr)

print("Reshaping array with zeroz extended")
matrix_arr.resize(3, 3) # If the size of array is larger then the size of previous array then it will extend zeros
print(matrix_arr)


Pritn 1 by 7 array
[1 2 3 4 5 6]
Reshape the matrix given above
[[1 2 3]
 [4 5 6]]
Array after reshping the array
[[1 2 3]
 [4 5 6]]
Reshaping array with zeroz extended
[[1 2 3]
 [4 5 6]
 [0 0 0]]


**numpy.ndarray.flat**

In [126]:
import numpy as np

matrix_arr = np.arange(9).reshape(3,3)
print(matrix_arr)

print("It create a 1-d array iterator over theh given array")
print(matrix_arr.flat[1:3])

print("Replace the 1:3 elements of above array with 2")
matrix_arr.flat[1:3]=2
print(matrix_arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
It create a 1-d array iterator over theh given array
[1 2]
Replace the 1:3 elements of above array with 2
[[0 2 2]
 [3 4 5]
 [6 7 8]]
